export const MESSAGES_FETCH_STARTED = 'MESSAGES_FETCH_STARTED'
export const MESSAGES_FETCH_SUCCESS = 'MESSAGES_FETCH_SUCCESS'
export const MESSAGES_FETCH_FAIL = 'MESSAGES_FETCH_FAIL'

export const MESSAGE_SEND_STARTED = 'MESSAGE_SEND_STARTED'
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS'
export const MESSAGE_SEND_FAIL = 'MESSAGE_SEND_FAIL'

export const MESSAGE_RECEIVE_STARTED = 'MESSAGE_RECEIVE_STARTED'
export const MESSAGE_RECEIVE_SUCCESS = 'MESSAGE_RECEIVE_SUCCESS'
export const MESSAGE_RECEIVE_FAIL = 'MESSAGE_RECEIVE_FAIL'

export const BALANCE_FETCH_STARTED = 'BALANCE_FETCH_STARTED'
export const BALANCE_FETCH_SUCCESS = 'BALANCE_FETCH_SUCCESS'
export const BALANCE_FETCH_FAIL = 'BALANCE_FETCH_FAIL'
